name: Continuous Integration
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: make templates
      - run: pip3 install cocotb
      - run: |
          git clone https://github.com/wallento/cocotbext-wishbone.git
          pip3 install -e cocotbext-wishbone
      - run: make templates
      - run: make unit-tests 
