name: Continuous Integration
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@main
      - name: Compile and install iverilog 
        run: |
          sudo apt install -y gperf
          git clone https://github.com/steveicarus/iverilog.git
          cd iverilog
          sh autoconf.sh
          ./configure
          make -j$(nproc)
          make install
      - name: Install cocotb and modules
        run: |
          pip3 install cocotb
          git clone https://github.com/wallento/cocotbext-wishbone.git
          pip3 install -e cocotbext-wishbone
      - name: Run tests
        run: |
          make templates
          make unit-tests 
