name: Verible formatter
on:
  pull_request:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: mole99/verible-formatter-action@main
      with:
        paths: design/wfg_drive_spi/*/*.sv design/wfg_stim_sine/*/*.sv
        github_token: ${{ secrets.GITHUB_TOKEN }}
