name: Verible formatter
on:
  pull_request:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: mole99/verible-formatter-action@main
      with:
        parameters:
          --indentation_spaces 4
          --module_net_variable_alignment=preserve
          --case_items_alignment=preserve
        paths: design/*/*/*.sv
        github_token: ${{ secrets.GITHUB_TOKEN }}
