name: Verible linter
on: [push]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: mole99/verible-linter-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        config_file: 'config.rules'
        fail_on_error: true
        suggest_fixes: 'false'
        paths: |
          ./design/
        extra_args: "--check_syntax=true --rules=-unpacked-dimensions-range-ordering"
    - name: Log output
      run: cat verible-verilog-lint.log
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: linter-log
        path: verible-verilog-lint.log
